package bzha2709.comp5216.sydney.edu.au.runningdiary.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bzha2709.comp5216.sydney.edu.au.runningdiary.POJO.TrackPoint;
import bzha2709.comp5216.sydney.edu.au.runningdiary.POJO.StepRecord;

import bzha2709.comp5216.sydney.edu.au.runningdiary.db.TrackPointDao;
import bzha2709.comp5216.sydney.edu.au.runningdiary.db.StepRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackPointDaoConfig;
    private final DaoConfig stepRecordDaoConfig;

    private final TrackPointDao trackPointDao;
    private final StepRecordDao stepRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackPointDaoConfig = daoConfigMap.get(TrackPointDao.class).clone();
        trackPointDaoConfig.initIdentityScope(type);

        stepRecordDaoConfig = daoConfigMap.get(StepRecordDao.class).clone();
        stepRecordDaoConfig.initIdentityScope(type);

        trackPointDao = new TrackPointDao(trackPointDaoConfig, this);
        stepRecordDao = new StepRecordDao(stepRecordDaoConfig, this);

        registerDao(TrackPoint.class, trackPointDao);
        registerDao(StepRecord.class, stepRecordDao);
    }
    
    public void clear() {
        trackPointDaoConfig.clearIdentityScope();
        stepRecordDaoConfig.clearIdentityScope();
    }

    public TrackPointDao getTrackPointDao() {
        return trackPointDao;
    }

    public StepRecordDao getStepRecordDao() {
        return stepRecordDao;
    }

}
