package bzha2709.comp5216.sydney.edu.au.runningdiary.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bzha2709.comp5216.sydney.edu.au.runningdiary.POJO.TrackPoint;

import bzha2709.comp5216.sydney.edu.au.runningdiary.db.TrackPointDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackPointDaoConfig;

    private final TrackPointDao trackPointDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackPointDaoConfig = daoConfigMap.get(TrackPointDao.class).clone();
        trackPointDaoConfig.initIdentityScope(type);

        trackPointDao = new TrackPointDao(trackPointDaoConfig, this);

        registerDao(TrackPoint.class, trackPointDao);
    }
    
    public void clear() {
        trackPointDaoConfig.clearIdentityScope();
    }

    public TrackPointDao getTrackPointDao() {
        return trackPointDao;
    }

}
